---
- name: Hyprland - install
  become: true
  become_user: root
  ansible.builtin.package:
    name:
      - hyprland
      - hyprpaper
      - hypridle
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland
      - qt5-wayland
      - qt6-wayland
      - wl-clipboard
      - grim
      - slurp
      - yq
    state: present
  notify: Rkhunter propupdate

- name: Hyprland - install aur packages
  kewlfft.aur.aur:
    use: yay
    name:
      - hyprprop-git
      - hyprpicker
      - pyprland
      - clipse
    state: present
  notify: Rkhunter propupdate
  become: true
  become_user: aur_builder

# Symlink Files
- name: Hyprland - create config directory
  ansible.builtin.file:
    path: ~/.config/hypr
    state: directory
    mode: "0777"

- name: Hyprland - find files to symlink
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/roles/ui-hyprland/files/hypr"
    file_type: any
  register: hypr_files

- name: Hyprland - symlink files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "~/.config/hypr/{{ item.path | basename }}"
    state: link
    follow: false
    force: true
    mode: "0777"
  with_items: "{{ hypr_files.files }}"

- name: Hyprland - create xdg-portal config directory
  ansible.builtin.file:
    path: ~/.config/xdg-desktop-portal
    state: directory
    mode: "0777"

- name: Hyprland - symlink files
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/ui-hyprland/files/{{ item }}"
    dest: "~/.config/xdg-desktop-portal/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - hyprland-portals.conf
