---
- name: AMD - Drivers Pacman
  become: true
  become_user: root
  pacman:
    update_cache: true
    name:
      - xf86-video-amdgpu
      - vulkan-radeon
      - lib32-vulkan-radeon
      - vulkan-tools
      - opencl-clover-mesa
      - lib32-opencl-clover-mesa
      - libva-mesa-driver
      - lib32-libva-mesa-driver
      - mesa
      - lib32-mesa
      - mesa-vdpau
      - lib32-mesa-vdpau
      - vdpauinfo
      - clinfo
      - rocm-hip-sdk

# AUR
- name: AMD - Drivers AUR
  kewlfft.aur.aur:
    use: yay
    name:
      - amf-amdgpu-pro
      - vulkan-amdgpu-pro
  become: true
  become_user: aur_builder
