---
- name: ZSH - create config directory
  ansible.builtin.file:
    path: "~/.config/.zsh"
    state: directory
    mode: "0777"

- name: ZSH - symlink config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/zsh/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    follow: false
    force: true
  loop:
    - .zshrc

- name: ZSH - symlink aliases
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/terminal/files/zsh/{{ item }}"
    dest: "~/.config/.zsh/{{ item }}"
    state: link
    follow: false
    force: true
  with_items:
    - .zshaliases

- name: ZSH - add ssh agent persistence
  ansible.builtin.lineinfile:
    path: "~/.zshrc"
    line: "ssh-add --apple-use-keychain ~/.ssh/id_ssh_default 2>/dev/null"
    create: true
    insertafter: EOF
